server:
  port: 8080
spring:
  cloud:
   gateway:
     routes:
      - id: api1
        uri: http://localhost:8081
        predicates:
         - Path=/api1/**
        filters:
         - RewritePath=/api1/(?<path>.*), /$\{path}
      - id: api2
        uri: http://localhost:8082
        predicates:
         - Path=/api2/**
        filters:
         - RewritePath=/api2/(?<path>.*), /$\{path}
  main:
      web-application-type: reactive